#!/data/data/com.termux/files/usr/bin/bash
yes | termux-setup-storage > dev/null

yes | pkg install python ffmpeg atomicparsley git

yes | pip install youtube-dl

value="true"; key="allow-external-apps"; file="/data/data/com.termux/files/home/.termux/termux.properties"; mkdir -p "$(dirname "$file")"; chmod 700 "$(dirname "$file")"; if ! grep -E '^'"$key"'=.*' $file &>/dev/null; then [[ -s "$file" && ! -z "$(tail -c 1 "$file")" ]] && newline=$'\n' || newline=""; echo "$newline$key=$value" >> "$file"; else sed -i'' -E 's/^'"$key"'=.*/'"$key=$value"'/' $file; fi

cd

rm -rf ytdl

git clone -b work https://github.com/Practicalbutterfly5/ytdl.git

chmod -R +x ytdl

mkdir bin

cp ytdl/termux-url-opener bin

mkdir -p /sdcard/Tasker/ytdl

cp ytdl/ytdl.prj.xml /sdcard/Tasker/ytdl/

echo -e "\n\n------------------------------\nStarting to import Tasker project.\n------------------------------\n\n"

am start -n net.dinglisch.android.taskerm/com.joaomgcd.taskerm.datashare.import.ActivityImportTaskerDataFromXml -d "file:///sdcard/Tasker/ytdl/ytdl.prj.xml"
