#!/data/data/com.termux/files/usr/bin/bash

# $1 is name of video, delimiter |
# $2 is ids of video, delimiter |
# $3 is download directory 
# $4 is resolution
# $5 is mode

#name=$(printf "%s" "$1" | LC_ALL=C sed -e 's/[^a-zA-Z0-9,._+@%/-]/\\&/g; 1{$s/^$/""/}; 1!s/^/"/; $!s/$/"/';)

IFS="|" read -a array <<< "$1"
IFS="|" read -a array2 <<< "$2"
for i in "${!array[@]}"; do
cat > /sdcard/Tasker/ytdl/"${array2[i]}" << EOF
$5
${array2[i]}
${array[i]}
$3
$4
$$
EOF

am broadcast --user '0' -a tasker.ytdl -e downloading "1"

if [ "$5" = "audio" ]
then
bash -c 'echo "$$" & exec youtube-dl --newline --embed-thumbnail -f "bestaudio[ext=m4a]/bestaudio" -o "/sdcard/Tasker/ytdl/tmp/%(title)s.m4a" -- "$0" ' "${array2[i]}" >>/sdcard/Tasker/ytdl/"${array2[i]}"
else
bash -c 'echo "$$" & exec youtube-dl --newline  -f "bestvideo[height<="$1"][ext=mp4]+bestaudio[ext=m4a]/best[height<="$1"][ext=mp4]/best" -o "/sdcard/Tasker/ytdl/tmp/%(title)s.mp4" -- "$0" ' "${array2[i]}" "$4" >>/sdcard/Tasker/ytdl/"${array2[i]}"
fi

errorcode="$?"
if [ $errorcode == 0 ]
then
 echo "Download complete">>/sdcard/Tasker/ytdl/"${array2[i]}"
 else
 echo "Download failed">>/sdcard/Tasker/ytdl/"${array2[i]}"
 fi
done
